module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    screens: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      black: '#000',
      white: '#fff',
      navBar: 'var(--nav-bar-color)',
      onNavBar: 'var(--on-nav-bar-color)',
      primary: 'var(--primary-color)',
      primaryVariant: 'var(--primary-color-variant)',
      secondary: 'var(--secondary-color)',
      secondaryVariant: 'var(--secondary-color-variant)',
      background: 'var(--background-color)',
      surface: 'var(--surface-color)',
      error: 'var(--error-color)',
      onPrimary: 'var(--on-primary-color)',
      onSecondary: 'var(--on-secondary-color)',
      onBackground: 'var(--on-background-color)',
      onSurface: 'var(--on-surface-color)',
      onError: 'var(--on-error-color)',
    },
    extend: {},
  },
  variants: {
    extend: {},
  },
  corePlugins: {
    gradientColorStops: false,
    fontFamily: false,
    placeholderColor: false,
    placeholderOpacity: false,
    transform: false,
    transformOrigin: false,
    scale: false,
    rotate: false,
    translate: false,
    skew: false,
    ringWidth: false,
    ringOpacity: false,
    ringColor: false,
    ringOffsetWidth: false,
    ringOffsetColor: false,
    divideStyle: false,
    divideOpacity: false,
    divideColor: false,
    divideWidth: false,
    mixBlendMode: false,
    backgroundBlendMode: false,
    transitionProperty: false,
    transitionDuration: false,
    transitionTimingFunction: false,
    transitionDelay: false,
    animation: false,
    accessibility: false,
    hueRotate: false,
    invert: false,
    saturate: false,
    sepia: false,
    backdropFilter: false,
    backdropBlur: false,
    backdropBrightness: false,
    backdropContrast: false,
    backdropGrayscale: false,
    backdropHueRotate: false,
    backdropInvert: false,
    backdropOpacity: false,
    backdropSaturate: false,
    backdropSepia: false,
    space: false,
    textOpacity: false,
    brightness: false,
    contrast: false,
    hueRotate: false,     scale: false,
  },
  plugins: [],
}